package au.csiro.obr17q.variantspark;

import org.junit.Assert._
import org.junit.Test;

class MetaDataParserTest {

	@Test	def test1000GenomeLikeData() {
    val CSV = Iterator(
        "sample\tpop\tsuper_pop\tgender",
        "HG00096\ta1\tEUR\tmale",
        "HG00097\ta1\tEUR\tfemale",
        "HG00098\ta2\tEUR\tfemale",
        "HG00099\ta2\tEUR\tfemale",
        "HG00100\tb1\tEUR\tfemale",
        "HG00101\tb2\tEUR\tmale",
        "HG00102\tb2\tEUR\tfemale",
        "HG00102\tc1\tEUR\tfemale",
        "HG00102\tc2\tEUR\tfemale"
    )

		val metas = new MetaDataParser(CSV, 1, '\t', "NA", 0, 1)

		assertEquals("The output should be a count of individuals.", 9, metas.returnMap().length)
    assertEquals("The output should be a count of individuals who belong to a1.", 2, metas.returnMap(IncludeGroups = Array("a1")).length)
    assertEquals("The output should be a count of individuals who belong to a1 or a2.", 4, metas.returnMap(IncludeGroups = Array("a1", "a2")).length)
    assertEquals("The output should be a count of individuals who belong to a1 or a2.", 4, metas.returnMap(IncludeGroups = Array("a1", "a2"), ExcludeGroups = Array("")).length)
    assertEquals("The output should be a count of individuals who belong to a1 or a2.", 4, metas.returnMap(IncludeGroups = Array("a1", "a2"), ExcludeGroups = Array("b1", "b2")).length)
    assertEquals("The output should be a count of individuals who belong to a1 or a2.", 4, metas.returnMap(IncludeGroups = Array("a1", "a2", "c1"), ExcludeGroups = Array("c1")).length)
    assertEquals("The output should be a count of individuals who belong to a1 or a2 or c1.", 5, metas.returnMap(IncludeGroups = Array("a1", "a2", "c1")).length)
    assertEquals("The output should be a count of individuals who do not belong to b1.", 8, metas.returnMap(ExcludeGroups = Array("b1")).length)
    assertEquals("The output should be a count of individuals who do not belong to b1 or b2.", 6, metas.returnMap(ExcludeGroups = Array("b1", "b2")).length)
	}
  
  
  
  @Test def testTCGALikeData() {
    val CSV = Iterator(
        "bcr_patient_uuid\tbcr_patient_barcode\tform_completion_date\thistologic_diagnosis\tprospective_collection\tretrospective_collection\tgender\tbirth_days_to\trace\tethnicity\thistory_other_malignancy\thistory_neoadjuvant_treatment\tinitial_pathologic_dx_year\tajcc_staging_edition\tajcc_tumor_pathologic_pt\tajcc_nodes_pathologic_pn\tajcc_metastasis_pathologic_pm\tajcc_pathologic_tumor_stage\tresidual_tumor\tlymph_nodes_examined_count\tlymph_nodes_examined\tlymph_nodes_examined_he_count\tlymph_nodes_examined_ihc_count\tvital_status\tlast_contact_days_to\tdeath_days_to\ttumor_status\tcea_level_pretreatment\tspecimen_non_node_tumor_deposits\tcircumferential_resection_margin_crm\tvascular_invasion_indicator\tlymphovascular_invasion_indicator\tperineural_invasion\tmicrosatellite_instability\tloci_tested_count\tloci_abnormal_count\tmismatch_rep_proteins_tested_by_ihc\tmismatch_rep_proteins_loss_ihc\tkras_gene_analysis_indicator\tkras_mutation_found\tkras_mutation_codon\tbraf_gene_analysis_indicator\tbraf_gene_analysis_result\thistory_other_malignancy\thistory_colon_polyps\tcolon_polyps_at_procurement_indicator\tweight_kg_at_diagnosis\theight_cm_at_diagnosis\tfamily_history_colorectal_cancer\tradiation_treatment_adjuvant\tpharmaceutical_tx_adjuvant\ttreatment_outcome_first_course\tnew_tumor_event_dx_indicator\tage_at_initial_pathologic_diagnosis\tanatomic_neoplasm_subdivision\tanatomic_neoplasm_subdivision_other\tclinical_M\tclinical_N\tclinical_T\tclinical_stage\tdays_to_first_complete_response\tdays_to_first_partial_response\tdays_to_first_response\tdays_to_initial_pathologic_diagnosis\tdays_to_patient_progression_free\tdays_to_tumor_progression\tdisease_code\teastern_cancer_oncology_group\ter_disease_extent_prior_er_treatment\ter_estimated_duration_response\ter_response_type\ter_solid_tumor_response_documented_type\ter_solid_tumor_response_documented_type_other\textranodal_involvement\tfield\thistological_type_other\thistory_of_radiation_metastatic_site\thistory_of_radiation_primary_site\thistory_prior_surgery_indicator\thistory_prior_surgery_type\thistory_prior_surgery_type_other\ticd_10\ticd_o_3_histology\ticd_o_3_site\tinformed_consent_verified\tinitial_pathologic_diagnosis_method\tkarnofsky_performance_score\tmolecular_abnormality_results\tmolecular_abnormality_results_other\tnumber_pack_years_smoked\tpatient_id\tpatient_progression_status\tproject_code\tstage_other\tstopped_smoking_year\ttissue_source_site\ttobacco_smoking_history\ttumor_tissue_site\tyear_of_tobacco_smoking_onset",
        "bcr_patient_uuid\tbcr_patient_barcode\tform_completion_date\thistological_type\ttissue_prospective_collection_indicator\ttissue_retrospective_collection_indicator\tgender\tdays_to_birth\trace\tethnicity\tprior_dx\thistory_of_neoadjuvant_treatment\tyear_of_initial_pathologic_diagnosis\tsystem_version\tpathologic_T\tpathologic_N\tpathologic_M\tpathologic_stage\tresidual_tumor\tprimary_lymph_node_presentation_assessment\tlymph_node_examined_count\tnumber_of_lymphnodes_positive_by_he\tnumber_of_lymphnodes_positive_by_ihc\tvital_status\tdays_to_last_followup\tdays_to_death\tperson_neoplasm_cancer_status\tpreoperative_pretreatment_cea_level\tnon_nodal_tumor_deposits\tcircumferential_resection_margin\tvenous_invasion\tlymphatic_invasion\tperineural_invasion_present\tmicrosatellite_instability\tnumber_of_loci_tested\tnumber_of_abnormal_loci\tloss_expression_of_mismatch_repair_proteins_by_ihc\tloss_expression_of_mismatch_repair_proteins_by_ihc_result\tkras_gene_analysis_performed\tkras_mutation_found\tkras_mutation_codon\tbraf_gene_analysis_performed\tbraf_gene_analysis_result\tsynchronous_colon_cancer_present\thistory_of_colon_polyps\tcolon_polyps_present\tweight\theight\tnumber_of_first_degree_relatives_with_cancer_diagnosis\tradiation_therapy\tpostoperative_rx_tx\tprimary_therapy_outcome_success\tnew_tumor_event_after_initial_treatment\tage_at_initial_pathologic_diagnosis\tanatomic_neoplasm_subdivision\tanatomic_neoplasm_subdivision_other\tclinical_M\tclinical_N\tclinical_T\tclinical_stage\tdays_to_first_complete_response\tdays_to_first_partial_response\tdays_to_first_response\tdays_to_initial_pathologic_diagnosis\tdays_to_patient_progression_free\tdays_to_tumor_progression\tdisease_code\teastern_cancer_oncology_group\ter_disease_extent_prior_er_treatment\ter_estimated_duration_response\ter_response_type\ter_solid_tumor_response_documented_type\ter_solid_tumor_response_documented_type_other\textranodal_involvement\tfield\thistological_type_other\thistory_of_radiation_metastatic_site\thistory_of_radiation_primary_site\thistory_prior_surgery_indicator\thistory_prior_surgery_type\thistory_prior_surgery_type_other\ticd_10\ticd_o_3_histology\ticd_o_3_site\tinformed_consent_verified\tinitial_pathologic_diagnosis_method\tkarnofsky_performance_score\tmolecular_abnormality_results\tmolecular_abnormality_results_other\tnumber_pack_years_smoked\tpatient_id\tpatient_progression_status\tproject_code\tstage_other\tstopped_smoking_year\ttissue_source_site\ttobacco_smoking_history\ttumor_tissue_site\tyear_of_tobacco_smoking_onset",
        "CDE_ID:\tCDE_ID:2673794\tCDE_ID:\tCDE_ID:3081934\tCDE_ID:3088492\tCDE_ID:3088528\tCDE_ID:2200604\tCDE_ID:3008233\tCDE_ID:2192199\tCDE_ID:2192217\tCDE_ID:3382736\tCDE_ID:3382737\tCDE_ID:2896960\tCDE_ID:2722309\tCDE_ID:3045435\tCDE_ID:3203106\tCDE_ID:3045439\tCDE_ID:3203222\tCDE_ID:2608702\tCDE_ID:2200396\tCDE_ID:3\tCDE_ID:3086388\tCDE_ID:3086383\tCDE_ID:5\tCDE_ID:3008273\tCDE_ID:3165475\tCDE_ID:2759550\tCDE_ID:2716510\tCDE_ID:3107051\tCDE_ID:64202\tCDE_ID:64358\tCDE_ID:64171\tCDE_ID:64181\tCDE_ID:3123142\tCDE_ID:3107127\tCDE_ID:3107129\tCDE_ID:3123153\tCDE_ID:3105496\tCDE_ID:3123147\tCDE_ID:2932340\tCDE_ID:3124509\tCDE_ID:3123151\tCDE_ID:3107189\tCDE_ID:2185953\tCDE_ID:3107197\tCDE_ID:64184\tCDE_ID:651\tCDE_ID:649\tCDE_ID:3107205\tCDE_ID:2005312\tCDE_ID:3397567\tCDE_ID:2786727\tCDE_ID:3121376\tCDE_ID:2006657\tCDE_ID:3108203\tCDE_ID:2584114\tCDE_ID:3440331\tCDE_ID:3440330\tCDE_ID:3440328\tCDE_ID:3440332\tCDE_ID:4887531\tCDE_ID:4887532\tCDE_ID:4887523\tCDE_ID:3131740\tCDE_ID:4887491\tCDE_ID:3165480\tCDE_ID:\tCDE_ID:88\tCDE_ID:2007719\tCDE_ID:1098\tCDE_ID:2187835\tCDE_ID:4101853\tCDE_ID:4129472\tCDE_ID:3364582\tCDE_ID:\tCDE_ID:3124492\tCDE_ID:2332\tCDE_ID:2182189\tCDE_ID:1071\tCDE_ID:4297170\tCDE_ID:3121814\tCDE_ID:3226287\tCDE_ID:3226275\tCDE_ID:3226281\tCDE_ID:2714689\tCDE_ID:2757941\tCDE_ID:2003853\tCDE_ID:3121628\tCDE_ID:4500214\tCDE_ID:2955385\tCDE_ID:\tCDE_ID:4381042\tCDE_ID:\tCDE_ID:2007104\tCDE_ID:2228610\tCDE_ID:\tCDE_ID:2181650\tCDE_ID:3427536\tCDE_ID:2228604",
        "A94E1279-A975-480A-93E9-7B1FF05CBCBF\tTCGA-3L-AA1B\t2014-4-22\tColon Adenocarcinoma\tYES\tNO\tFEMALE\t-22379\tBLACK OR AFRICAN AMERICAN\tNOT HISPANIC OR LATINO\tNo\tNo\t2013\t7th\tT2\tN0\tM0\tStage I\tR0\tYES\t28\t0\t0\tAlive\t154\t[Not Applicable]\tTUMOR FREE\t[Not Available]\tNO\t[Not Available]\tNO\tNO\tNO\tNO\t[Not Available]\t[Not Available]\tYES\tMLH1 Expressed|MSH2 Expressed|PMS2 Expressed|MSH6 Expressed\tNO\t[Not Available]\t[Not Available]\tNO\t[Not Available]\tNO\tYES\tYES\t63.3\t173\t0\tNO\tNO\tComplete Remission/Response\tNO\t61\tCecum\t[Not Available]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t0\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tC18.0\t8140/3\tC18.0\tYES\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tAA1B\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t3L\t[Not Available]\tColon\t[Not Available]",
        "92554413-9EBC-4354-8E1B-9682F3A031D9\tTCGA-4N-A93T\t2014-10-1\tColon Adenocarcinoma\tYES\tNO\tMALE\t-24523\tBLACK OR AFRICAN AMERICAN\tNOT HISPANIC OR LATINO\tNo\tNo\t2013\t7th\tT4a\tN1b\tM0\tStage IIIB\tR0\tYES\t25\t[Not Available]\t2\tAlive\t8\t[Not Applicable]\tWITH TUMOR\t2.0\tYES\t30\tNO\tNO\tNO\t[Unknown]\t[Not Available]\t[Not Available]\tYES\tMLH1 Expressed|MSH2 Expressed|PMS2 Expressed|MSH6 Expressed\tNO\t[Not Available]\t[Not Available]\tNO\t[Not Available]\tYES\tNO\tYES\t134\t167.64\t0\tNO\tYES\tStable Disease\tNO\t67\tAscending Colon\t[Not Available]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t0\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tC18.2\t8140/3\tC18.2\tYES\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tA93T\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t4N\t[Not Available]\tColon\t[Not Available]",
        "A5E14ADD-1552-4606-9FFE-3A03BCF76640\tTCGA-4T-AA8H\t2014-6-5\tColon Mucinous Adenocarcinoma\tNO\tYES\tFEMALE\t-15494\tBLACK OR AFRICAN AMERICAN\tNOT HISPANIC OR LATINO\tNo\tNo\t2013\t7th\tT3\tN0\tMX\tStage IIA\tR0\tYES\t24\t0\t[Not Available]\tAlive\t160\t[Not Applicable]\tTUMOR FREE\t[Not Available]\tNO\t20\tNO\tNO\tNO\tNO\t[Not Available]\t[Not Available]\tYES\tMLH1 Expressed|MSH2 Expressed|PMS2 Expressed|MSH6 Expressed\tNO\t[Not Available]\t[Not Available]\tNO\t[Not Available]\tNO\tNO\tNO\t107.956\t167.6\t0\tNO\tNO\tComplete Remission/Response\tNO\t42\tDescending Colon\t[Not Available]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t0\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tC18.6\t8480/3\tC18.6\tYES\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tAA8H\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t4T\t[Not Available]\tColon\t[Not Available]",
        "1136DD50-242A-4659-AAD4-C53F9E759BB3\tTCGA-5M-AAT4\t2015-1-27\tColon Adenocarcinoma\tNO\tYES\tMALE\t-27095\tBLACK OR AFRICAN AMERICAN\tHISPANIC OR LATINO\tNo\tNo\t2009\t6th\tT3\tN0\tM1b\tStage IV\tR0\tYES\t3\t0\t0\tDead\t[Not Available]\t49\tWITH TUMOR\t550.0\tNO\t[Not Available]\tYES\t[Unknown]\t[Unknown]\t[Unknown]\t[Not Available]\t[Not Available]\tNO\t[Not Available]\tNO\t[Not Available]\t[Not Available]\tNO\t[Not Available]\tNO\tNO\tYES\t[Not Available]\t[Not Available]\t0\tNO\tNO\tProgressive Disease\tNO\t74\tAscending Colon\t[Not Available]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t0\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Applicable]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tC18.2\t8140/3\tC18.2\tYES\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\tAAT4\t[Not Available]\t[Not Available]\t[Not Available]\t[Not Available]\t5M\t[Not Available]\tColon\t[Not Available]"

    )

    val metas = new MetaDataParser(CSV, 3, '\t', "[Not Available]", 0, 1)(WeightCol = 46, HeightCol = 47)

    assertEquals("The output should be a count of individuals.", 4, metas.returnMap().length)
    
    assertEquals("Weight of first.", 63, metas.returnMap()(0).Weight, 1)
    assertEquals("Height of first.", 173, metas.returnMap()(0).Height, 1)
    assertEquals("BMI of first.", 21, metas.returnMap()(0).BMI, 1)

    assertEquals("Weight of second.", 134, metas.returnMap()(1).Weight, 1)
    assertEquals("Height of second.", 167, metas.returnMap()(1).Height, 1)
    assertEquals("BMI of second.", 48, metas.returnMap()(1).BMI, 1)

    assertEquals("Weight of third.", 107, metas.returnMap()(2).Weight, 1)
    assertEquals("Height of third.", 167, metas.returnMap()(2).Height, 1)
    assertEquals("BMI of third.", 38, metas.returnMap()(2).BMI, 1)

    assertEquals("Weight of fourth is NA so should be 0.", 0, metas.returnMap()(3).Weight, 1)
    assertEquals("Height of fourth is NA so should be 0.", 0, metas.returnMap()(3).Height, 1)
    assertEquals("Weight and/or Height are NA so should be 0.", 0, metas.returnMap()(3).BMI, 1)
  }  
}
